### ISSUE TITLE
RuntimeError: CUDA error: no kernel image 

### ISSUE THREAD

**Issue by youngfly** [mit-han-lab/bevfusion#267]
Hello, I encountered problem as solved in https://github.com/mit-han-lab/bevfusion/issues/26 when I  test model <torchpack dist-run -np 8 python3 tools/test.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth --eval bbox>

  **File "/root/paddlejob/workspace/yyr/code/bevfusion-main/mmdet3d/ops/voxel/voxelize.py", line 55, in forward
    voxel_num = hard_voxelize(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.**

**Besides, this problem is existing when I train the lidar detection and fusion detection. However, the camera detection training is ok.**

I have tried the below operations mentioned in other issue. All of them are useless.
1) Removing lines and python setup.py develop again
            "-gencode=arch=compute_70,code=sm_70",
            "-gencode=arch=compute_75,code=sm_75",
            "-gencode=arch=compute_80,code=sm_80",
            "-gencode=arch=compute_86,code=sm_86",
2) Add the lines (corresponding to Nvidia P40) and remoiving others, and python setup.py develop again
            "-gencode=arch=compute_61,code=sm_61",

3) I just replace the code [here](https://github.com/mit-han-lab/bevfusion/blob/main/configs/nuscenes/default.yaml#L261) with samples_per_gpu: 2. This time, I also replace the next line with workers_per_gpu: 2, and did the replacement you mentioned.

my CUDA version is 10.0.
GPU:Nvidia P40
pytorch:1.9.0
other required libraries are installed indicated in your README

More detail is below
Traceback (most recent call last):
  File "tools/train.py", line 87, in <module>
    main()
  File "tools/train.py", line 76, in main
    train_model(
  File "/root/paddlejob/workspace/yyr/code/bevfusion-main/mmdet3d/apis/train.py", line 126, in train_model
    runner.run(data_loaders, [("train", 1)])
  File "/root/anaconda3/envs/bevfusion/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/paddlejob/workspace/yyr/code/bevfusion-main/mmdet3d/runner/epoch_based_runner.py", line 14, in train
    super().train(data_loader, **kwargs)
  File "/root/anaconda3/envs/bevfusion/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/root/anaconda3/envs/bevfusion/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/root/anaconda3/envs/bevfusion/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 52, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/root/paddlejob/workspace/yyr/code/bevfusion-main/mmdet3d/models/fusion_models/base.py", line 78, in train_step
    losses = self(**data)
  File "/root/anaconda3/envs/bevfusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/bevfusion/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/root/paddlejob/workspace/yyr/code/bevfusion-main/mmdet3d/models/fusion_models/bevfusion.py", line 187, in forward
    outputs = self.forward_single(
  File "/root/anaconda3/envs/bevfusion/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/root/paddlejob/workspace/yyr/code/bevfusion-main/mmdet3d/models/fusion_models/bevfusion.py", line 244, in forward_single
    feature = self.extract_lidar_features(points)
  File "/root/paddlejob/workspace/yyr/code/bevfusion-main/mmdet3d/models/fusion_models/bevfusion.py", line 130, in extract_lidar_features
    feats, coords, sizes = self.voxelize(x)
  File "/root/anaconda3/envs/bevfusion/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/bevfusion/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 214, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/root/paddlejob/workspace/yyr/code/bevfusion-main/mmdet3d/models/fusion_models/bevfusion.py", line 140, in voxelize
    ret = self.encoders["lidar"]["voxelize"](res)
  File "/root/anaconda3/envs/bevfusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/paddlejob/workspace/yyr/code/bevfusion-main/mmdet3d/ops/voxel/voxelize.py", line 131, in forward
    return voxelization(
  **File "/root/paddlejob/workspace/yyr/code/bevfusion-main/mmdet3d/ops/voxel/voxelize.py", line 55, in forward
    voxel_num = hard_voxelize(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.**

**Comment by kentang-mit** [comment]
Hello @youngfly , I think this error is caused by lines 22-25 in [this file](https://github.com/mit-han-lab/bevfusion/blob/3d91980d21556bf697f51b717875d0a31e5be2dd/setup.py#L22). Feel free to remove these lines and rerun

```bash
python setup.py develop
```

This is because Tesla P40 is a GPU with Pascal architecture, while our compiler flags only compile for Volta+.

**Comment by youngfly** [comment]
Hello, I have doen as you said "remove these lines and rerun"， but it does not work when testing or training. The Same issue is below.

  **File "/root/paddlejob/workspace/yyr/code/bevfusion-main/mmdet3d/ops/voxel/voxelize.py", line 131, in forward
    return voxelization(
  File "/root/paddlejob/workspace/yyr/code/bevfusion-main/mmdet3d/ops/voxel/voxelize.py", line 55, in forward
    voxel_num = hard_voxelize(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.**

Besides, the complile process is below. Is any thing wrong?

(bevfusion) [root@yq01-sys-hic-k8s-standard-p40-0028 bevfusion-main]# python setup.py develop
running develop
running egg_info
writing mmdet3d.egg-info/PKG-INFO
writing dependency_links to mmdet3d.egg-info/dependency_links.txt
writing top-level names to mmdet3d.egg-info/top_level.txt
/root/anaconda3/envs/bevfusion/lib/python3.8/site-packages/torch/utils/cpp_extension.py:370: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'mmdet3d.egg-info/SOURCES.txt'
writing manifest file 'mmdet3d.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.8/mmdet3d/ops/spconv/sparse_conv_ext.cpython-38-x86_64-linux-gnu.so -> mmdet3d/ops/spconv
copying build/lib.linux-x86_64-3.8/mmdet3d/ops/bev_pool/bev_pool_ext.cpython-38-x86_64-linux-gnu.so -> mmdet3d/ops/bev_pool
copying build/lib.linux-x86_64-3.8/mmdet3d/ops/iou3d/iou3d_cuda.cpython-38-x86_64-linux-gnu.so -> mmdet3d/ops/iou3d
copying build/lib.linux-x86_64-3.8/mmdet3d/ops/voxel/voxel_layer.cpython-38-x86_64-linux-gnu.so -> mmdet3d/ops/voxel
copying build/lib.linux-x86_64-3.8/mmdet3d/ops/roiaware_pool3d/roiaware_pool3d_ext.cpython-38-x86_64-linux-gnu.so -> mmdet3d/ops/roiaware_pool3d
copying build/lib.linux-x86_64-3.8/mmdet3d/ops/ball_query/ball_query_ext.cpython-38-x86_64-linux-gnu.so -> mmdet3d/ops/ball_query
copying build/lib.linux-x86_64-3.8/mmdet3d/ops/knn/knn_ext.cpython-38-x86_64-linux-gnu.so -> mmdet3d/ops/knn
copying build/lib.linux-x86_64-3.8/mmdet3d/ops/paconv/assign_score_withk_ext.cpython-38-x86_64-linux-gnu.so -> mmdet3d/ops/paconv
copying build/lib.linux-x86_64-3.8/mmdet3d/ops/group_points/group_points_ext.cpython-38-x86_64-linux-gnu.so -> mmdet3d/ops/group_points
copying build/lib.linux-x86_64-3.8/mmdet3d/ops/interpolate/interpolate_ext.cpython-38-x86_64-linux-gnu.so -> mmdet3d/ops/interpolate
copying build/lib.linux-x86_64-3.8/mmdet3d/ops/furthest_point_sample/furthest_point_sample_ext.cpython-38-x86_64-linux-gnu.so -> mmdet3d/ops/furthest_point_sample
copying build/lib.linux-x86_64-3.8/mmdet3d/ops/gather_points/gather_points_ext.cpython-38-x86_64-linux-gnu.so -> mmdet3d/ops/gather_points
Creating /root/anaconda3/envs/bevfusion/lib/python3.8/site-packages/mmdet3d.egg-link (link to .)
mmdet3d 0.0.0 is already the active version in easy-install.pth

Installed /root/paddlejob/workspace/yyr/code/bevfusion-main
Processing dependencies for mmdet3d==0.0.0
Finished processing dependencies for mmdet3d==0.0.0

**Comment by kentang-mit** [comment]
It doesn't seem that you are re-compiling any CUDA extensions. What about removing the `build` directory and trying again?

**Comment by youngfly** [comment]
You are right, I have fixed the problem. Before we change the setup.py  lines 22-25 in [this file](https://github.com/mit-han-lab/bevfusion/blob/3d91980d21556bf697f51b717875d0a31e5be2dd/setup.py#L22) and python setup.py develop, we should remove the build directory each time.（this is very important）

I have doen below
1、remove the build directory
2、change the setup.py  lines 22-25 （according to our corresponding to Nvidia P40）
    Add the lines "-gencode=arch=compute_61,code=sm_61", and remoiving others,
3、python setup.py develop again
