### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`

### ISSUE THREAD

**Issue by lingxe01** [mit-han-lab/bevfusion#602]
I ran into this error when I tried to train, my cuda version is 11.3 and torch version is 1.10.1

**Comment by Sun-Jiahao** [comment]
I got the same error. Have you fixed it? @lingxe01

**Comment by Sun-Jiahao** [comment]
Same problem as #615 . Also, I solved it by downgrading my cuda environment from 11.3 to 11.1. See [https://developer.nvidia.com/cuda-11.1.0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_distro=Ubuntu&target_version=2004&target_type=deblocal](url)
